# Generated by Django 5.2.5 on 2025-08-13 23:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('higiene', 'Higiene Bucal'), ('alimentacao', 'Alimentação'), ('prevencao', 'Prevenção'), ('tratamento', 'Tratamento'), ('criancas', 'Para Crianças')], max_length=20)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='conteudo/')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('cad_unico', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do CadÚnico')),
                ('tipo_usuario', models.CharField(choices=[('paciente', 'Paciente'), ('responsavel', 'Responsável'), ('estudante', 'Estudante de Odontologia'), ('profissional', 'Profissional de Saúde')], default='paciente', max_length=20)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.TextField()),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(default='Santo Antônio de Jesus', max_length=100)),
                ('estado', models.CharField(default='BA', max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MensagemSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('respondida', 'Respondida'), ('fechada', 'Fechada')], default='aberta', max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('resposta', models.TextField(blank=True, null=True)),
                ('estudante', models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'estudante'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_atendidas', to='educa_sorriso.perfilusuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='educa_sorriso.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('higiene', 'Higiene Bucal'), ('consulta', 'Consulta Odontológica'), ('prevencao', 'Prevenção'), ('tratamento', 'Acompanhamento de Tratamento')], max_length=20)),
                ('data_lembrete', models.DateTimeField()),
                ('lido', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='educa_sorriso.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('tipo_consulta', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('faltou', 'Faltou')], default='agendada', max_length=20)),
                ('data_agendamento', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='educa_sorriso.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_preenchimento', models.DateTimeField(auto_now_add=True)),
                ('possui_alergias', models.BooleanField(default=False)),
                ('alergias_descricao', models.TextField(blank=True, null=True)),
                ('medicamentos_uso', models.TextField(blank=True, null=True)),
                ('problemas_saude', models.TextField(blank=True, null=True)),
                ('ultima_consulta', models.DateField(blank=True, null=True)),
                ('frequencia_escovacao', models.CharField(blank=True, max_length=50, null=True)),
                ('usa_fio_dental', models.BooleanField(default=False)),
                ('frequencia_fio_dental', models.CharField(blank=True, max_length=50, null=True)),
                ('problemas_bucais', models.TextField(blank=True, null=True)),
                ('dor_dentes', models.BooleanField(default=False)),
                ('sangramento_gengiva', models.BooleanField(default=False)),
                ('problemas_odontologicos_familia', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to='educa_sorriso.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('correta', models.BooleanField(default=False)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='educa_sorriso.perguntaquiz')),
            ],
        ),
        migrations.AddField(
            model_name='perguntaquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='educa_sorriso.quiz'),
        ),
        migrations.CreateModel(
            name='ResultadoQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.IntegerField()),
                ('total_perguntas', models.IntegerField()),
                ('data_realizacao', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='educa_sorriso.quiz')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_quiz', to='educa_sorriso.perfilusuario')),
            ],
        ),
    ]
